###### Environment section ######

- name: Install packages for certbot
  ansible.builtin.apt:
    name:
      - "{{ gcc }}"
      - "{{ libaugeas_dev }}"
      - "{{ python }}"
      - "{{ python_dev }}"
      - "{{ python_venv }}"
    state: "present"
  tags: ["certbot", "install"]

- name: Prevent specific packages from being updated (Hold)
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - "{{ gcc }}"
    - "{{ libaugeas_dev }}"
    - "{{ python }}"
    - "{{ python_dev }}"
    - "{{ python_venv }}"
  tags: ["certbot", "install"]

- name: Create certbot venv
  ansible.builtin.command: "{{ python }} -m venv /opt/certbot"
  args:
    creates: "/opt/certbot/bin/activate"
  tags: ["certbot"]

- name: Upgrade pip in venv
  ansible.builtin.pip:
    name: "pip"
    state: "present"
    virtualenv: "/opt/certbot"
  tags: ["certbot", "install"]

###### Apt section ######

- name: Install latest version of certbot and plugins
  ansible.builtin.pip:
    name:
      - "certbot"
      - "certbot-dns-cloudflare"
    virtualenv: "/opt/certbot"
  tags: ["certbot", "install"]

- name: Install latest version of certbot and plugins
  ansible.builtin.pip:
    name:
      - "certbot-nginx"
    virtualenv: "/opt/certbot"
  when: "'mail' in group_names"
  tags: ["certbot", "install"]

###### Environment section ######

- name: Symlink certbot binary
  ansible.builtin.file:
    src: "/opt/certbot/bin/certbot"
    dest: "/usr/bin/certbot"
    state: "link"
    force: "yes"
  tags: ["certbot", "file"]

- name: Ensure secrets directory exists
  ansible.builtin.file:
    path: "/root/.secrets/certbot"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0700"
  tags: ["certbot", "file"]

- name: Create cloudflare credential files
  ansible.builtin.copy:
    dest: "/root/.secrets/certbot/{{ item.filename }}"
    content: |
      dns_cloudflare_api_token = {{ item.token }}
    owner: "root"
    group: "root"      
    mode: "0600"
  loop: "{{ cert_and_mail_data }}"
  no_log: true
  tags: ["certbot", "file"]

###### MAIL Certificate section ######

- name: Obtain certificate for all domains
  ansible.builtin.command: >
    certbot certonly
    --dns-cloudflare
    --dns-cloudflare-credentials /root/.secrets/certbot/{{ item.filename }}
    --dns-cloudflare-propagation-seconds 60
    -d {{ item.cert_domain }}
    --non-interactive
    --agree-tos
    -m {{ mail_for_certbot }}
  args:
    creates: "/etc/letsencrypt/live/{{ item.cert_domain }}/fullchain.pem"
  loop: "{{ cert_and_mail_data }}"
  no_log: true
  when: "'mail' in group_names"
  tags: ["certbot"]

###### LOGS Certificate section ######

- name: Obtain certificate for all domains
  ansible.builtin.command: >
    certbot certonly
    --dns-cloudflare
    --dns-cloudflare-credentials /root/.secrets/certbot/{{ item.filename }}
    --dns-cloudflare-propagation-seconds 60
    -d {{ item.cert_domain }}
    --non-interactive
    --agree-tos
    -m {{ mail_for_certbot }}
  args:
    creates: "/etc/letsencrypt/live/{{ item.cert_domain }}/fullchain.pem"
  loop: "{{ cert_private_data }}"
  no_log: true
  when: "'logs' in group_names"
  tags: ["certbot"]

###### Handler section ######

- name: Certbot renew cron
  ansible.builtin.cron:
    name: "certbot renew"
    job: "/usr/bin/certbot renew --quiet"
    minute: "0"
    hour: "3"
  tags: ["certbot"]

- name: Certbot update cron
  ansible.builtin.cron:
    name: "certbot update"
    job: "/opt/certbot/bin/pip install --upgrade certbot certbot-dns-cloudflare"
    minute: "0"
    hour: "1"
    day: "7"
  tags: ["certbot"]

- name: Ensure Certbot deploy hooks directory exists
  ansible.builtin.file:
    path: "/etc/letsencrypt/renewal-hooks/deploy"
    state: "directory"
    mode: "0755"
  tags: ["certbot", "file"]

- name: Create Certbot renew deploy hook for mail services
  ansible.builtin.copy:
    dest: "/etc/letsencrypt/renewal-hooks/deploy/reload-mail.sh"
    content: |
      #!/bin/bash
      set -e
      postmap -F hash:/etc/postfix/sni-map.map
      systemctl reload dovecot
      systemctl reload postfix
    mode: "0755"
  when: "'mail' in group_names"
  tags: ["certbot", "file"]

- name: Create Certbot renew deploy hook for private services
  ansible.builtin.copy:
    dest: "/etc/letsencrypt/renewal-hooks/deploy/reload-private.sh"
    content: |
      DOMAIN_NAME="{{ cert_private_data[0].cert_domain }}"
      
      cp /etc/letsencrypt/live/$DOMAIN_NAME/cert.pem {{ wazuh_dashboard_cert_dir }}/server-crt.pem
      cp /etc/letsencrypt/live/$DOMAIN_NAME/fullchain.pem {{ wazuh_dashboard_cert_dir }}/server-fullchain.pem
      cp /etc/letsencrypt/live/$DOMAIN_NAME/privkey.pem {{ wazuh_dashboard_cert_dir }}/server-key.pem
      
      cp /etc/letsencrypt/live/$DOMAIN_NAME/cert.pem {{ grafana_cert_dir }}/server-crt.pem
      cp /etc/letsencrypt/live/$DOMAIN_NAME/fullchain.pem {{ grafana_cert_dir }}/server-fullchain.pem
      cp /etc/letsencrypt/live/$DOMAIN_NAME/privkey.pem {{ grafana_cert_dir }}/server-key.pem
      
      chown root:wazuh-dashboard {{ wazuh_dashboard_cert_dir }}/server-*.pem
      chown root:grafana {{ grafana_cert_dir }}/server-*.pem

      systemctl restart grafana-server
      systemctl restart loki
      systemctl restart prometheus
      systemctl restart wazuh-dashboard
    mode: "0755"
  when: "'logs' in group_names"
  tags: ["certbot", "file"]