#################################
#                               #
#        # Comment              #
#        variable: "value"      #
#                               #
#################################
# All credentials are stored in vault.yaml files which are encrypted using .vault_pass file


####### System #######
# Password that will be set as root password
root_password: "{{ vault_root_password }}"
# Name of the user that was created at the installation process of system (sudo user)
new_admin_user: "kubernetes_user"
# Password for sudo user is stored in installer/host_vars/inventory_name/vault.yaml
new_admin_password: "{{ vault_new_admin_password }}"
# User used to connect to host using SSH
ansible_user: "{{ new_admin_user }}"
# Password used by ansible to execute sudo commands
ansible_become_password: "{{ new_admin_password }}"

####### Logrotate #######
# Name of file template that contains all logrotate rules
logrotate_file: "slave"