- name: Begin installation on logs server
  hosts: logs
  gather_facts: false
  pre_tasks:
    - name: Gather minimal facts as regular user (No sudo required)
      setup:
        gather_subset:
          - min
      become: false
      tags: ["always"]

    - name: Dynamically set sudo executable based on Ubuntu version
      set_fact:
        ansible_become_exe: "{{ 'sudo.ws' if (ansible_facts['distribution_major_version'] == '26') else 'sudo' }}"
      become: false
      tags: ["always"]

    - name: Dynamically set become
      set_fact:
        ansible_become: true
      become: false
      tags: ["always"]
  roles:
    - wazuh_indexer
    - wazuh_manager
    - wazuh_dashboard
    - grafana
    - loki
    - prometheus
    - clamav

- name: Begin installation on mail server
  hosts: mail
  gather_facts: false
  pre_tasks:
    - name: Gather minimal facts as regular user (No sudo required)
      setup:
        gather_subset:
          - min
      become: false
      tags: ["always"]
      
    - name: Dynamically set sudo executable based on Ubuntu version
      set_fact:
        ansible_become_exe: "{{ 'sudo.ws' if (ansible_facts['distribution_major_version'] == '26') else 'sudo' }}"
      become: false
      tags: ["always"]

    - name: Dynamically set become
      set_fact:
        ansible_become: true
      become: false
      tags: ["always"]
  roles:
    - system
    - certbot
    - nginx
    - php
    - roundcube
    - mysql
    - redis
    - rspamd
    - postfix
    - dovecot
    - fail2ban
    - wazuh_agent

- name: Actions for all devices
  hosts: lan
  gather_facts: false
  pre_tasks:
    - name: Gather minimal facts as regular user (No sudo required)
      setup:
        gather_subset:
          - min
      become: false
      tags: ["always"]

    - name: Dynamically set sudo executable based on Ubuntu version
      set_fact:
        ansible_become_exe: "{{ 'sudo.ws' if (ansible_facts['distribution_major_version'] == '26') else 'sudo' }}"
      become: false
      tags: ["always"]

    - name: Dynamically set become
      set_fact:
        ansible_become: true
      become: false
      tags: ["always"]
  roles:
    - alloy
    - logrotate
    - iptables

- name: Perfom package cleaning
  hosts: lan
  gather_facts: false
  pre_tasks:
    - name: Gather minimal facts as regular user (No sudo required)
      setup:
        gather_subset:
          - min
      become: false
      tags: ["always"]

    - name: Dynamically set sudo executable based on Ubuntu version
      set_fact:
        ansible_become_exe: "{{ 'sudo.ws' if (ansible_facts['distribution_major_version'] == '26') else 'sudo' }}"
      become: false
      tags: ["always"]

    - name: Dynamically set become
      set_fact:
        ansible_become: true
      become: false
      tags: ["always"]
  tasks:
    - name: Clean packages
      ansible.builtin.apt:
        clean: true
      tags: ["always"]

    - name: Remove dependencies that are no longer required and purge their configuration files
      ansible.builtin.apt:
        autoremove: yes
        purge: true
      tags: ["always"]

###### Tags ######

# Specific modules only                                   just name of the role for example clamav or certs
# Only install packages                                   install
# Only copy or replace files/templates                    file
# Commands that should run one time (not install)           once
# Systemctl actions                                       handler
